In [2]:
%pip install scikit-learn

  Using cached scikit_learn-1.5.1-cp311-cp311-win_amd64.whl.metadata (12 kB)
  Using cached numpy-2.1.1-cp311-cp311-win_amd64.whl.metadata (59 kB)
  Using cached scipy-1.14.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.5.1-cp311-cp311-win_amd64.whl (11.0 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached numpy-2.1.1-cp311-cp311-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.8 MB 131.3 kB/s eta 0:05:41
   -------------------------------------


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.8 MB 82.2 kB/s eta 0:03:26
   ------------------------ --------------- 27.9/44.

In [1]:
from sklearn import datasets

iris_dataset = datasets.load_iris()

# iris_dataset is like a dictionary whose keys can be found using 
# print(iris_dataset.keys())
# dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
print(iris_dataset['feature_names'])
print(iris_dataset['data'][:5]) # Printing the first 5 rows using slicing

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
